const test = require('node:test');
const assert = require('node:assert/strict');
const { mkdtemp, writeFile } = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { pathToFileURL } = require('node:url');
const { PassThrough } = require('node:stream');
const { once } = require('node:events');
const { TempestTwitchExperiences } = require('../dist/twitch-experiences');

test('tracks Hype Train, Raid Portal, and goal overlay state independently', async () => {
  const dataDirectory = await mkdtemp(path.join(os.tmpdir(), 'tempest-experiences-'));
  const experiences = new TempestTwitchExperiences(dataDirectory);
  await experiences.initialize();
  const event = (id, topic, payload) => ({ schemaVersion: 1, id, topic, occurredAt: new Date().toISOString(), source: 'twitch', channel: { id: 'channel' }, payload });
  experiences.ingest(event('hype', 'channel.hype-train.updated', { phase: 'progress', level: 2, progress: 400, goal: 1000, total: 1400 }));
  experiences.ingest(event('goal', 'channel.goal.updated', { phase: 'progress', description: 'Signal Goal', currentAmount: 7, targetAmount: 10 }));
  experiences.ingest({ ...event('raid', 'viewer.raid.received', { fromBroadcasterId: 'raider', fromBroadcasterName: 'Raid Leader', viewers: 42 }), viewer: { id: 'raider', displayName: 'Raid Leader' } });
  let status = experiences.status('http://127.0.0.1/twitch-experiences');
  assert.deepEqual(status.active, { hypeTrain: true, raidPortal: true, goalOverlay: true });
  assert.equal(status.experienceState.raid.fromBroadcasterName, 'Raid Leader');
  assert.equal(status.settings.raidPortalDesign.preset, 'mainframe-breach');
  const mediaPath = path.join(dataDirectory, 'raid.gif');
  await writeFile(mediaPath, Buffer.from('GIF89a', 'ascii'));
  await experiences.update({ raidPortalEnabled: false, hypeAccent: '#112233', raidPortalDesign: { preset: 'tempest', mediaUri: pathToFileURL(mediaPath).href, mediaLayer: 'foreground', mediaFit: 'contain', mediaOpacity: 0.8, customHtml: '<b>{broadcaster}</b>', customCss: '#raid{filter:none}', customJavaScript: 'elements.section.dataset.custom = variables.broadcaster;' } });
  status = experiences.status('local');
  assert.equal(status.settings.raidPortalDesign.mediaLayer, 'foreground');
  const mediaResponse = new PassThrough();
  const headers = new Map();
  mediaResponse.setHeader = (name, value) => headers.set(name, value);
  const mediaChunks = [];
  mediaResponse.on('data', (chunk) => mediaChunks.push(chunk));
  const mediaFinished = once(mediaResponse, 'finish');
  assert.equal(await experiences.serveMedia('raid-portal', mediaResponse), true);
  await mediaFinished;
  assert.equal(headers.get('Content-Type'), 'image/gif');
  assert.deepEqual(Buffer.concat(mediaChunks), Buffer.from('GIF89a', 'ascii'));
  const overlayPage = experiences.page();
  assert.match(overlayPage, /SECURITY MAINFRAME \/\/ PERIMETER BREACH/);
  const inlineScript = overlayPage.match(/<script>([\s\S]+)<\/script>/)?.[1];
  assert.ok(inlineScript);
  assert.doesNotThrow(() => Function(inlineScript));
  await assert.rejects(() => experiences.update({ raidPortalDesign: { ...status.settings.raidPortalDesign, customHtml: '<script>alert(1)</script>' } }), /JavaScript field/);
  await assert.rejects(() => experiences.update({ raidPortalDesign: { ...status.settings.raidPortalDesign, customJavaScript: 'if (' } }), /customJavaScript is invalid/);
  experiences.clear();
  experiences.preview('raid-portal');
  status = experiences.status('local');
  assert.equal(status.active.raidPortal, false, 'disabled experiences do not activate during previews');
  experiences.preview('hype-train');
  assert.equal(experiences.status('local').active.hypeTrain, true);
  experiences.close();
});
