packages:
  - "apps/*"
  - "packages/*"
  - "services/*"

overrides:
  js-yaml: 4.3.2

onlyBuiltDependencies:
  - electron
allowBuilds:
  '@3d-dice/dice-box': false
  electron: true
  electron-winstaller: true
