const test = require('node:test');
const assert = require('node:assert/strict');
const { readFile } = require('node:fs/promises');
const path = require('node:path');

test('renderer includes orchestration and management sections with a restrictive content security policy', async () => {
  const html = await readFile(path.join(__dirname, '..', 'dist', 'renderer', 'index.html'), 'utf8');
  const renderer = await readFile(path.join(__dirname, '..', 'dist', 'renderer', 'app.js'), 'utf8');
  const main = await readFile(path.join(__dirname, '..', 'dist', 'main.js'), 'utf8');
  const preload = await readFile(path.join(__dirname, '..', 'dist', 'preload.js'), 'utf8');
  assert.match(html, /Studio Home/);
  assert.match(html, /What would you like to work on/);
  assert.match(html, /id="onboardingDialog"/);
  assert.match(html, /Guided Setup/);
  assert.match(html, /FIRST-RUN SETUP/);
  assert.match(renderer, /tempest\.streaming-studio\.onboarding\.v1/);
  assert.match(renderer, /Browser Sources/);
  assert.match(renderer, /3440 × 1440/);
  assert.match(renderer, /Interaction audio routed off the VOD track/);
  assert.match(renderer, /visual-alerts\/interactions/);
  assert.match(renderer, /visual-alerts\/twitch/);
  assert.match(renderer, /\/chat-overlay/);
  assert.match(html, /data-go="visualalerts"/);
  assert.match(html, /data-go="soundalerts"/);
  assert.match(html, /RUNTIME SNAPSHOT/);
  assert.match(html, /Interaction Workflows/);
  assert.match(html, /Event Log/);
  assert.match(html, /Twitch Gateway/);
  assert.match(html, /id="extensiondesignerSection"/);
  assert.match(html, /Twitch Panel Designer/);
  assert.match(html, /318 × 496 Twitch Panel/);
  assert.match(html, /Interaction Alerts/);
  assert.match(html, /New Interaction Alert/);
  assert.match(html, /id="interactionAlertForm"/);
  assert.match(html, /New Twitch Alert/);
  assert.match(html, /id="twitchAlertForm"/);
  assert.match(html, /id="twitchDesignDialog"/);
  assert.match(html, /id="twitchPlacementCanvas"/);
  assert.match(html, /id="twitchDesignScale"/);
  assert.match(html, /Custom — drag anywhere/);
  assert.match(html, /3440 × 1440 · 43:18 BROWSER SOURCE/);
  assert.match(html, /TWITCH ALERT DESIGNER/);
  assert.match(html, /Advanced HTML, CSS &amp; JavaScript/);
  assert.match(html, /\{viewer\}/);
  assert.match(html, /data-section="visualalerts"/);
  assert.match(html, /id="visualalertsSection"/);
  assert.match(html, /data-section="chatoverlay"/);
  assert.match(html, /id="chatoverlaySection"/);
  assert.match(html, /STUDIO-OWNED STREAM CHAT/);
  assert.match(html, /without a Botrix browser source/);
  assert.match(html, /Twitch Alerts/);
  assert.match(html, /PERFORMANCE \+ DANCE CATALOG/);
  assert.match(html, /TWITCH CHANNEL EVENTS/);
  assert.match(html, /Design the complete sound-and-visual response/);
  assert.match(html, /GIPHY KEY REQUIRED/);
  assert.match(html, /100 API calls \/ hour/);
  assert.match(html, /id="giphyResultSummary"/);
  assert.match(html, /DOWNLOADS LOCALLY/);
  assert.match(html, /Powered by GIPHY/);
  assert.match(html, /Stored with Windows encryption/);
  assert.match(html, /Connect Warudo/);
  assert.match(html, /Tempest Performance Cue/);
  assert.match(html, /Test Activate/);
  assert.match(html, /Test Release/);
  assert.match(html, /tempestPerformance/);
  assert.match(html, /ws:\/\/localhost:4770/);
  assert.match(html, /ALWAYS FREE/);
  assert.match(html, /Control audio via OBS/);
  assert.match(html, /VOD-safe routing/);
  assert.match(html, /Alert Queue/);
  assert.match(renderer, /Clear Waiting/);
  assert.match(renderer, /\/v1\/alert-queue\/clear/);
  assert.match(renderer, /route this source off the YouTube\/VOD track/);
  assert.match(renderer, /Interaction Alert browser-source URL/);
  assert.match(renderer, /Twitch Alert browser-source URL/);
  assert.match(html, /Waiting for its live OBS source inventory/);
  assert.match(renderer, /sourceInventory/);
  assert.match(renderer, /broadcastAudioSourceOptions/);
  assert.match(renderer, /Test Interaction/);
  assert.match(renderer, /Assign Sound/);
  assert.match(renderer, /data-interaction-alert-save/);
  assert.match(renderer, /data-twitch-alert-audio/);
  assert.match(renderer, /Customize Design/);
  assert.match(renderer, /data-interaction-alert-design/);
  assert.match(renderer, /openInteractionDesignEditor/);
  assert.match(renderer, /warudoEnabled/);
  assert.match(html, /id="newInteractionWarudoEnabled"/);
  assert.match(renderer, /INTERACTION ALERT DESIGNER/);
  assert.match(html, /Place, size, and preview the alert/);
  assert.match(renderer, /defaultTwitchDesign/);
  assert.match(renderer, /saveTwitchDesign/);
  assert.match(renderer, /savePanelDesign/);
  assert.match(renderer, /updatePanelDesignPreview/);
  assert.match(renderer, /updateTwitchPlacementPreview/);
  assert.match(renderer, /beginTwitchPlacementInteraction/);
  assert.match(html, /Text layered over media/);
  assert.match(html, /twitchDesignTextPositionX/);
  assert.match(html, /twitchDesignTextPositionY/);
  assert.match(html, /data-design-code-tab="html"/);
  assert.match(html, /data-design-code-tab="css"/);
  assert.match(html, /data-design-code-tab="javascript"/);
  assert.match(renderer, /customJavaScript/);
  assert.match(renderer, /deleteInteractionAlert/);
  assert.match(renderer, /deleteTwitchAlert/);
  assert.match(renderer, /method: 'POST'.*\/v1\/sound-alerts/s);
  assert.match(renderer, /Assign Visual/);
  assert.match(renderer, /\/v1\/visual-alerts/);
  assert.match(renderer, /data-visual-alert-effect/);
  assert.match(renderer, /data-visual-alert-circuit/);
  assert.match(renderer, /data-visual-alert-strength/);
  assert.match(renderer, /Preview Alert/);
  assert.match(renderer, /Preview Alert/);
  assert.match(renderer, /\/v1\/visual-alerts\/twitch/);
  assert.match(renderer, /searchGiphy/);
  assert.match(renderer, /importGiphyVisual/);
  assert.match(renderer, /copyToClipboard/);
  assert.match(renderer, /data-copy-text/);
  assert.match(main, /clipboard\.writeText/);
  assert.match(preload, /studio:copy-text/);
  assert.match(preload, /studio:save-twitch-panel-design/);
  assert.match(main, /twitch-panel-design\.json/);
  assert.match(main, /tempest-twitch-auth-/);
  assert.match(main, /clearStorageData/);
  assert.match(main, /studio:open-isolated-twitch-authorization/);
  assert.match(main, /studio:close-isolated-twitch-authorization/);
  assert.match(preload, /studio:open-isolated-twitch-authorization/);
  assert.match(preload, /studio:close-isolated-twitch-authorization/);
  assert.match(html, /Open Isolated Sign-In/);
  assert.match(html, /temporary sign-in cookies are erased/);
  assert.match(renderer, /\/v1\/chat-overlay/);
  assert.match(html, /Preview Message/);
  assert.match(html, /OAuth authorization, refresh, expiry/);
  assert.match(html, /DEVICE AUTHORIZATION/);
  assert.match(html, /EXTENSION RELAY/);
  assert.match(html, /SINGLE-CHANNEL EXTENSION/);
  assert.match(html, /Start Local Panel/);
  assert.match(html, /type="password"/);
  assert.match(html, /Windows encryption/);
  assert.match(html, /BUILD 0\.11\.6/);
  assert.match(html, /id="chatbotAllowSharedChat"/);
  assert.match(html, /id="chatbotTestOrigin"/);
  assert.match(html, /Reply directly to viewer/);
  assert.match(html, /Seattle time and weather/);
  assert.match(html, /SECOND TWITCH ACCOUNT REQUIRED/);
  assert.match(html, /id="chatbotDisplayName"/);
  assert.match(html, /verified Twitch username/);
  assert.doesNotMatch(html, /Connect TempestMainframe/);
  assert.match(html, /COMMAND SIMULATOR/);
  assert.match(renderer, /\/v1\/chatbot\/oauth\/device/);
  assert.match(renderer, /displayName/);
  assert.match(renderer, /\/v1\/chatbot\/commands/);
  assert.match(html, /Connections/);
  assert.doesNotMatch(html, /data-section="warudo"/);
  assert.doesNotMatch(html, /id="warudoSection"/);
  assert.ok(html.indexOf('id="apiSection"') < html.indexOf('id="warudoOverallBadge"'), 'Warudo setup belongs inside Connections');
  assert.match(html, /ALERTS \+ OVERLAYS/);
  assert.match(html, /CHANNEL \+ APPS/);
  assert.match(html, /Software Management/);
  assert.match(html, /APPLICATIONS \+ LINKED SERVICES/);
  assert.match(renderer, /\/v1\/integrations\/storm-horizon-radio/);
  assert.match(renderer, /Storm Horizon Radio/);
  assert.match(renderer, /Open Public Player/);
  assert.match(renderer, /data-radio-player/);
  assert.match(html, /Asset Control/);
  assert.match(html, /Emergency Restore/);
  assert.match(html, /default-src 'self'/);
  assert.match(html, /media-src 'self' file:/);
  assert.doesNotMatch(html, /nodeIntegration\s*:\s*true/);
});
