const test = require('node:test');
const assert = require('node:assert/strict');
const { readFile } = require('node:fs/promises');
const path = require('node:path');

test('renderer includes orchestration and management sections with a restrictive content security policy', async () => {
  const html = await readFile(path.join(__dirname, '..', 'dist', 'renderer', 'index.html'), 'utf8');
  const renderer = await readFile(path.join(__dirname, '..', 'dist', 'renderer', 'app.js'), 'utf8');
  const main = await readFile(path.join(__dirname, '..', 'dist', 'main.js'), 'utf8');
  const preload = await readFile(path.join(__dirname, '..', 'dist', 'preload.js'), 'utf8');
  const styles = await readFile(path.join(__dirname, '..', 'dist', 'renderer', 'styles.css'), 'utf8');
  assert.match(html, /Studio Home/);
  assert.match(html, /What would you like to work on/);
  assert.match(html, /id="onboardingDialog"/);
  assert.match(html, /Guided Setup/);
  assert.match(html, /FIRST-RUN SETUP/);
  assert.match(renderer, /tempest\.streaming-studio\.onboarding\.v1/);
  assert.match(renderer, /Browser Sources/);
  assert.match(renderer, /Standard HD — 1920 × 1080/);
  assert.match(renderer, /broadcastCanvasProfile/);
  assert.match(renderer, /activeCanvasProfile/);
  assert.match(renderer, /Interaction audio routed off the VOD track/);
  assert.match(renderer, /visual-alerts\/interactions/);
  assert.match(renderer, /visual-alerts\/twitch/);
  assert.match(renderer, /\/chat-overlay/);
  assert.match(renderer, /\/emote-wall/);
  assert.match(html, /Emote Wall/);
  assert.match(html, /id="emoteWallMaxActive"/);
  assert.match(html, /id="emoteWallSevenTv"/);
  assert.match(html, /BetterTTV/);
  assert.match(html, /FrankerFaceZ/);
  assert.match(renderer, /emote-wall\/providers\/refresh/);
  assert.match(renderer, /Emote Wall browser-source URL/);
  assert.match(html, /Hype Train Takeover, Raid Portal \+ Goals/);
  assert.match(html, /id="twitchExperienceRaidDuration"/);
  assert.match(renderer, /\/v1\/twitch-experiences/);
  assert.match(renderer, /Twitch Experiences browser-source URL/);
  assert.doesNotMatch(html, /class="nav-button[^>]*>\s*<span>\d+/);
  assert.match(html, /<p class="nav-group">STREAM DESIGN<\/p>/);
  assert.match(html, /<p class="nav-group">CONNECTIONS<\/p>/);
  assert.match(html, /<p class="nav-group">TOOLS \+ RECORDS<\/p>/);
  assert.match(html, /data-go="visualalerts"/);
  assert.match(html, /data-go="soundalerts"/);
  assert.match(html, /RUNTIME SNAPSHOT/);
  assert.doesNotMatch(html, /data-section="workflows"/);
  assert.doesNotMatch(html, /id="workflowsSection"/);
  assert.doesNotMatch(html, /data-section="software"/);
  assert.doesNotMatch(html, /id="softwareSection"/);
  assert.doesNotMatch(html, /data-section="assets"/);
  assert.doesNotMatch(html, /id="assetsSection"/);
  assert.doesNotMatch(renderer, /renderWorkflows|renderSoftware|renderAssets/);
  assert.doesNotMatch(renderer, /\/v1\/assets/);
  assert.match(html, /Event Log/);
  assert.match(html, /Twitch Gateway/);
  assert.match(html, /streamers do not need a developer account, Client ID, or Client Secret/);
  assert.match(html, /Leave blank to use the official Tempest application/);
  assert.match(renderer, /No developer account is needed/);
  assert.match(html, /id="extensiondesignerSection"/);
  assert.match(html, /Twitch Panel Designer/);
  assert.match(html, /318 × 496 Twitch Panel/);
  assert.match(html, /Interaction Alerts/);
  assert.match(html, /New Interaction Alert/);
  assert.match(html, /id="interactionAlertForm"/);
  assert.match(html, /New Twitch Alert/);
  assert.match(html, /id="twitchAlertForm"/);
  assert.match(html, /id="twitchDesignDialog"/);
  assert.match(html, /id="twitchVariantDialog"/);
  assert.match(html, /Portable Alert Packs/);
  assert.match(html, /Alert History &amp; Diagnostics/);
  assert.match(html, /DURABLE PLAYBACK LEDGER/);
  assert.match(html, /BACKUP \+ MIGRATION/);
  assert.match(html, /Create Backup/);
  assert.match(html, /Restore Backup/);
  assert.match(html, /studioDataVersion/);
  assert.match(renderer, /dataMigration/);
  assert.match(main, /runStudioDataMigrations/);
  assert.match(renderer, /exportStudioBackup/);
  assert.match(renderer, /restoreStudioBackup/);
  assert.match(main, /studio:export-backup/);
  assert.match(main, /studio:restore-backup/);
  assert.match(preload, /studio:restart-app/);
  assert.match(renderer, /renderAlertHistory/);
  assert.match(renderer, /\/v1\/alert-history/);
  assert.match(renderer, /\/v1\/alert-diagnostics/);
  assert.match(html, /Import Alert Pack/);
  assert.match(renderer, /exportAlertPack/);
  assert.match(renderer, /importAlertPack/);
  assert.match(main, /studio:export-alert-pack/);
  assert.match(main, /studio:import-alert-pack/);
  assert.match(preload, /studio:export-alert-pack/);
  assert.match(preload, /studio:import-alert-pack/);
  assert.match(html, /Higher priority rules are checked first/);
  assert.match(renderer, /Manage Variants/);
  assert.match(renderer, /variantConditionFromForm/);
  assert.match(renderer, /openTwitchVariantDesignEditor/);
  assert.match(html, /id="twitchPlacementCanvas"/);
  assert.match(html, /id="twitchDesignScale"/);
  assert.match(html, /Custom — drag anywhere/);
  assert.match(html, /id="alertDesignerCanvasProfile"/);
  assert.match(html, /TWITCH ALERT DESIGNER/);
  assert.match(html, /Advanced HTML, CSS &amp; JavaScript/);
  assert.match(html, /\{viewer\}/);
  assert.match(html, /data-section="visualalerts"/);
  assert.match(html, /id="visualalertsSection"/);
  assert.match(html, /data-section="chatoverlay"/);
  assert.match(html, /id="chatoverlaySection"/);
  assert.match(html, /STUDIO-OWNED STREAM CHAT/);
  assert.match(html, /independent local Browser Sources/);
  assert.match(html, /Twitch Alerts/);
  assert.match(html, /PERFORMANCE \+ DANCE CATALOG/);
  assert.match(html, /TWITCH CHANNEL EVENTS/);
  assert.match(html, /Design the complete sound-and-visual response/);
  assert.match(html, /GIPHY KEY REQUIRED/);
  assert.match(html, /100 API calls \/ hour/);
  assert.match(html, /id="giphyResultSummary"/);
  assert.match(html, /DOWNLOADS LOCALLY/);
  assert.match(html, /Powered by GIPHY/);
  assert.match(html, /Stored with Windows encryption/);
  assert.match(html, /Connect your avatar app/);
  assert.match(html, /Save Warudo Receiver/);
  assert.match(html, /VTube Studio/);
  assert.match(renderer, /authorizeVTubeStudio/);
  assert.match(renderer, /vtubeStudioHotkeyOptions/);
  assert.match(html, /Tempest Performance Cue/);
  assert.match(html, /Test Activate/);
  assert.match(html, /Test Release/);
  assert.match(html, /tempestPerformance/);
  assert.match(html, /ws:\/\/localhost:4770/);
  assert.match(html, /ALWAYS FREE/);
  assert.match(html, /Control audio via OBS/);
  assert.match(html, /VOD-safe routing/);
  assert.match(html, /Alert Queue/);
  assert.match(renderer, /Clear Waiting/);
  assert.match(renderer, /\/v1\/alert-queue\/clear/);
  assert.match(renderer, /route this source off the YouTube\/VOD track/);
  assert.match(renderer, /Interaction Alert browser-source URL/);
  assert.match(renderer, /Twitch Alert browser-source URL/);
  assert.match(html, /Waiting for its live OBS source inventory/);
  assert.match(renderer, /sourceInventory/);
  assert.match(renderer, /broadcastAudioSourceOptions/);
  assert.match(renderer, /Test Interaction/);
  assert.match(renderer, /Assign Sound/);
  assert.match(renderer, /data-interaction-alert-save/);
  assert.match(renderer, /data-twitch-alert-audio/);
  assert.match(renderer, /Customize Design/);
  assert.match(renderer, /data-interaction-alert-design/);
  assert.match(renderer, /openInteractionDesignEditor/);
  assert.match(renderer, /warudoEnabled/);
  assert.match(html, /id="newInteractionWarudoEnabled"/);
  assert.match(renderer, /INTERACTION ALERT DESIGNER/);
  assert.match(html, /Place and resize the alert/);
  assert.match(renderer, /defaultTwitchDesign/);
  assert.match(renderer, /saveTwitchDesign/);
  assert.match(renderer, /savePanelDesign/);
  assert.match(renderer, /updatePanelDesignPreview/);
  assert.match(renderer, /updateTwitchPlacementPreview/);
  assert.match(renderer, /beginTwitchPlacementInteraction/);
  assert.match(html, /Text layered over media/);
  assert.match(html, /twitchDesignTextPositionX/);
  assert.match(html, /twitchDesignTextPositionY/);
  assert.match(html, /data-design-code-tab="html"/);
  assert.match(html, /data-design-code-tab="css"/);
  assert.match(html, /data-design-code-tab="javascript"/);
  assert.match(renderer, /customJavaScript/);
  assert.match(renderer, /deleteInteractionAlert/);
  assert.match(renderer, /deleteTwitchAlert/);
  assert.match(renderer, /method: 'POST'.*\/v1\/sound-alerts/s);
  assert.match(renderer, /Assign Visual/);
  assert.match(renderer, /\/v1\/visual-alerts/);
  assert.match(renderer, /data-visual-alert-effect/);
  assert.match(renderer, /data-visual-alert-circuit/);
  assert.match(renderer, /data-visual-alert-strength/);
  assert.match(renderer, /Preview Alert/);
  assert.match(renderer, /Preview Alert/);
  assert.match(renderer, /\/v1\/visual-alerts\/twitch/);
  assert.match(renderer, /searchGiphy/);
  assert.match(renderer, /importGiphyVisual/);
  assert.match(renderer, /copyToClipboard/);
  assert.match(renderer, /data-copy-text/);
  assert.match(main, /clipboard\.writeText/);
  assert.match(preload, /studio:copy-text/);
  assert.match(preload, /studio:save-twitch-panel-design/);
  assert.match(main, /twitch-panel-design\.json/);
  assert.match(main, /tempest-twitch-auth-/);
  assert.match(main, /clearStorageData/);
  assert.match(main, /studio:open-isolated-twitch-authorization/);
  assert.match(main, /studio:close-isolated-twitch-authorization/);
  assert.match(preload, /studio:open-isolated-twitch-authorization/);
  assert.match(preload, /studio:close-isolated-twitch-authorization/);
  assert.match(html, /Open Isolated Sign-In/);
  assert.match(html, /temporary sign-in cookies are erased/);
  assert.match(renderer, /\/v1\/chat-overlay/);
  assert.match(html, /Preview Message/);
  assert.match(html, /OAuth authorization, refresh, expiry/);
  assert.match(html, /DEVICE AUTHORIZATION/);
  assert.match(html, /EXTENSION RELAY/);
  assert.match(html, /SINGLE-CHANNEL EXTENSION/);
  assert.match(html, /Start Local Panel/);
  assert.match(html, /type="password"/);
  assert.match(html, /Windows encryption/);
  assert.match(html, /BUILD 1\.0\.0/);
  assert.match(html, /id="settingsSection"/);
  assert.match(html, /Redacted diagnostics/);
  assert.match(html, /What leaves this computer/);
  assert.match(html, /id="privacyModeButton"/);
  assert.match(html, /id="streamerPrivacyMode"/);
  assert.match(html, /id="windowCaptureProtection"/);
  assert.match(html, /data-sensitive/);
  assert.match(renderer, /renderPrivacySettings/);
  assert.match(renderer, /savePrivacySettings/);
  assert.match(main, /setContentProtection/);
  assert.match(main, /privacy-settings\.json/);
  assert.match(main, /studio:get-privacy-settings/);
  assert.match(preload, /studio:save-privacy-settings/);
  assert.match(html, /Automatic updates/);
  assert.match(html, /id="checkForStudioUpdates"/);
  assert.match(html, /id="downloadStudioUpdate"/);
  assert.match(html, /id="installStudioUpdate"/);
  assert.match(renderer, /renderUpdateStatus/);
  assert.match(main, /autoDownload\s*=\s*false/);
  assert.match(main, /autoInstallOnAppQuit\s*=\s*false/);
  assert.match(main, /disableWebInstaller\s*=\s*true/);
  assert.match(main, /studio:check-for-updates/);
  assert.match(main, /quitAndInstall/);
  assert.match(preload, /studio:update-status/);
  assert.match(styles, /body\.streamer-privacy \[data-sensitive\]/);
  assert.match(renderer, /getAppInfo/);
  assert.match(renderer, /exportStudioDiagnostics/);
  assert.match(main, /studio:export-diagnostics/);
  assert.match(preload, /studio:open-data-directory/);
  assert.match(styles, /prefers-reduced-motion:reduce/);
  assert.match(styles, /:focus-visible/);
  assert.match(html, /id="chatbotAllowSharedChat"/);
  assert.match(html, /id="chatbotTestOrigin"/);
  assert.match(html, /Reply directly to viewer/);
  assert.match(html, /OPTIONAL RESPONSE PROVIDERS/);
  assert.match(html, /Local weather \(United States\)/);
  assert.match(html, /AzuraCast now playing/);
  assert.doesNotMatch(html, /Seattle time and weather/);
  assert.doesNotMatch(html, /Storm Horizon Radio — now playing/);
  assert.match(html, /SECOND TWITCH ACCOUNT REQUIRED/);
  assert.match(html, /RAID AUTOMATION/);
  assert.match(html, /moderator:manage:shoutouts/);
  assert.match(html, /id="chatbotRaidWelcomeMessage"/);
  assert.match(html, /id="chatbotRaidShoutoutEnabled"/);
  assert.match(renderer, /\/v1\/chatbot\/raid\/test/);
  assert.match(html, /ASSIGNED CREATORS/);
  assert.match(html, /id="chatbotFirstChatChannels"/);
  assert.match(html, /id="chatbotFirstChatEnabled"/);
  assert.match(html, /id="chatbotInteractionAccessMode"/);
  assert.match(html, /id="chatbotInteractionAllowStaff"/);
  assert.match(renderer, /firstChatShoutouts/);
  assert.match(renderer, /interactionAccess/);
  assert.match(html, /id="chatbotAutoModForm"/);
  assert.match(html, /AutoMod \+ link protection/);
  assert.match(html, /moderator:manage:chat_messages/);
  assert.match(html, /moderator:manage:banned_users/);
  assert.match(renderer, /\/v1\/chatbot\/automod\/test/);
  assert.match(renderer, /Chatbot AutoMod settings saved/);
  assert.match(renderer, /Chat Overlay browser-source URL/);
  assert.match(renderer, /<code data-sensitive>\$\{escapeHtml\(overlay\.url\)\}<\/code>/);
  assert.match(main, /setContentProtection/);
  assert.match(html, /id="chatbotDisplayName"/);
  assert.match(html, /verified Twitch username/);
  assert.doesNotMatch(html, /Connect TempestMainframe/);
  assert.match(html, /COMMAND SIMULATOR/);
  assert.match(renderer, /\/v1\/chatbot\/oauth\/device/);
  assert.match(renderer, /displayName/);
  assert.match(renderer, /\/v1\/chatbot\/commands/);
  assert.match(html, /Connections/);
  assert.doesNotMatch(html, /data-section="warudo"/);
  assert.doesNotMatch(html, /id="warudoSection"/);
  assert.ok(html.indexOf('id="apiSection"') < html.indexOf('id="warudoOverallBadge"'), 'Warudo setup belongs inside Connections');
  assert.match(html, /STREAM DESIGN/);
  assert.match(html, /TOOLS \+ RECORDS/);
  assert.doesNotMatch(html, /Software Management/);
  assert.doesNotMatch(html, /APPLICATIONS \+ LINKED SERVICES/);
  assert.doesNotMatch(renderer, /Storm Horizon Radio/);
  assert.doesNotMatch(html, /Asset Control/);
  assert.match(html, /Emergency Restore/);
  assert.match(html, /default-src 'self'/);
  assert.match(html, /media-src 'self' file:/);
  assert.doesNotMatch(html, /nodeIntegration\s*:\s*true/);
});
